config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
  # Defines the root path route ("/")
  unauthenticated :user do
    root to: 'splashs#index'
  end

  authenticated :user do
    root "groups#index", as: :authenticated_root
  end
  resources :user do
    resources :groups, only: %i[index new show create destroy] do
      resources :entities, only: %i[index new show create destroy]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Group
    can :create, Group
    can :write, Group

    can :read, Entity
    can :create, Entity

    return unless user.present?

    can :destroy, Group, user: user
    can :destroy, Entity, user:
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_and_belongs_to_many :groups, dependent: :destroy
  validates :name, :amount, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_one_attached :image
  has_many :entities, foreign_key: 'group_id', class_name: 'Entity'
  validates :name, presence: true, length: { maximum: 255 }

  def total_amount
    entities.sum(:amount)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :groups
  has_many :entities
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attr_writer :login

  validate :validate_username

  def validate_username
    errors.add(:username, :invalid) if User.where(email: username).exists?
  end

  def login
    @login || username || email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if (login = conditions.delete(:login))
      where(conditions.to_h).where(['lower(username) = :value OR lower(email) = :value',
                                    { value: login.downcase }]).first
    elsif conditions.key?(:username) || conditions.key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: %i[username name email password password_confirmation remember_me])
    devise_parameter_sanitizer.permit(:sign_in,
                                      keys: %i[login username password password_confirmation remember_me])
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[username name email password_confirmation current_password
                                               remember_me])
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: %i[edit update destroy]
  before_action :authenticate_user!, except: %i[show index]

  # GET /entities or /entities.json
  def index
    @group = Group.find(params[:group_id])
    @entity = Entity.where(group_id: params[:group_id]).order(created_at: :desc)
  end

  # GET /entities/1 or /entities/1.json
  def show
    @entity = Entity.find(params[:id])
  end

  # GET /entities/new
  def new
    @entity = Entity.new
    @group = Group.where(user_id: current_user.id)
  end

  # GET /entities/1/edit
  def edit; end

  # POST /entities or /entities.json
  def create
    @user = current_user

    @entity = @user.entities.new(entity_params)

    respond_to do |format|
      if @entity.save
        format.html { redirect_to user_group_entities_path(@user), notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entities/1 or /entities/1.json
  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to entity_url(@entity), notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1 or /entities/1.json
  def destroy
    @entity = Entity.find(params[:id])
    @entity.destroy

    respond_to do |format|
      format.html { redirect_to user_group_entities_path, notice: 'Entity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entity
    @entity = Entity.includes(:user, :groups).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def entity_params
    params.require(:entity).permit(:name, :amount, :user_id, :group_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token
  load_and_authorize_resource
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = Group.includes(:user, :entities).order(created_at: :desc)
  end

  # GET /groups/1 or /groups/1.json
  def show; end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id

    if @group.save
      flash[:notice] = 'Category was successfully created.'

      redirect_to user_groups_path(@group.user_id)
    else
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: @group.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :image, :icon)
  end
end

app/controllers/splashs_controller.rb
class SplashsController < ApplicationController
  def index; end
end

app/controllers/turbo_devise_controller.rb
# rubocop:disable all
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      if get?
        raise e
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end
#rubocop:enable all

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/entities/_entity.html.erb
<div id="<%= dom_id entity %>">
  <p>
    <strong>Name:</strong>
    <%= entity.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= entity.amount %>
  </p>

</div>

app/views/entities/_form.html.erb
<div class="container-fluid">
    <div class="row d-flex justify-content-center">
        <div class="col-12 my-4">
            <%= link_to raw('<i class="fa-solid fa-angle-left fa-2x"></i>'), root_path %>
           </div>
        <div class="col-12 d-flex justify-content-center">
          <% if entity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
        <% entity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
            
        </div>
        <div class="col-md-6  card p-4 m-5">
           <%=  form_with model:  entity, url: user_group_entities_path, data: { turbo:false } do |f| %>
           <%= f.text_field :name, placeholder:'Trnsaction Name', class: 'form-control p-3 my-3'%>
           <%= f.number_field :amount,  placeholder: 'Amount', min:'0',  class: 'form-control p-3 my-3'%>
           <div class="form-control p-3 my-3">
            <%= f.label :category %>
            <%= f.collection_select :group_id, Group.where(user_id: current_user.id).order(:name),:id,:name %>
          </div>
           <div class="d-flex justify-content-end">
            <%= f.submit "Save", disable_with: 'Submiting...', class:'btn btn-success p-3 d-flex justify-content-end' %>
           </div>
           <% end %>
        </div>
    </div>
</div>

app/views/entities/edit.html.erb
<h1>Editing entity</h1>

<%= render "form", entity: @entity %>

<br>

<div>
  <%= link_to "Show this entity", @entity %> |
  <%= link_to "Back to entities", entities_path %>
</div>

app/views/entities/index.html.erb
<section class="container-fluid my-4">
    <div class="row">
        <div class="col-12 my-1">
            <%= link_to raw('<i class="fa-solid fa-angle-left fa-2x"></i>'), root_path %>
            <h1 class="text-primary d-flex justify-content-center">TRANSACTIONS</h1>
             
        </div>
        <div class="col-12">
            <h3 class="d-flex justify-content-center py-2 px-5">
            </h3>
        </div>
        </div>
        <div class="col-12 container">
            <p class="text-primary d-flex justify-content-start">
                <% if @group.name.present? %>
                <h3 class="text-primary"><%= @group.name %></h3>
                <% end %>
            </p>
            <h4 class="d-flex justify-content-end " style= "margin-bottom: 15px; color: #434b54;"> Total Amount: 
                $<%= Entity.where(group_id: @group.id).reduce(0) { |sum, t| sum + t.amount+0.0}  %></h4>
         </div>
  <div class="container ">
    <% @entity.each do |t|  %>
        <%= link_to(user_group_entity_path(id: t.id), style: "text-decoration: none;") do %>

            <div class="  budget-item1 my-2 " style=" display: flex; padding: 5px; justify-content: space-between; border: none !important;box-shadow: -12px -6px 21px 8px #eee; height: auto; margin-bottom : 40px;">
               <div class="my-4 cat-icon col-3 d-flex justify-content-between trans-img-div">
                 <%= image_tag(@group.image, style:" width : 120px; height : 120px; text-decoration: none;") %>
               </div>
               <div class="d-column col-4 " style="display: flex; align-items : center; flex-direction: column; ">
                  <h4 class="my-4" style= "text-decoration: none; color: #434b54; text-transform: capitalize;"><%= t.name %></h4>
                   <p class="my-4" style= "text-decoration: none; color: lightblue;"><%= l t.created_at.to_date, format: :long %></p>
               </div>
               <div class="col-3">
                    <p class="my-4" style= "text-decoration: none; color : yellowgreen; font-weight: 600; font-size: 20px;">$<%= t.amount+0.00 %></p>
                </div>
             </div>
       <% end %>
    <% end %>
  </div>
</section>
<footer class="footer">
<%= link_to "Add Transaction", new_user_group_entity_path, class: "add-trans" %>
<%= link_to "Back", root_path, class: "add-trans", style: "margin-left: 10px; " %>
</footer>
           

app/views/entities/new.html.erb
<div class="container-fluid">
    <div class="row d-flex justify-content-center">
        <div class="col-12 my-4">
            <%= link_to raw('<i class="fa-solid fa-angle-left fa-2x"></i>'), root_path %>
           </div>
        <div class="col-12 d-flex justify-content-center">
            <% if @entity.errors.any?  %>
            <%= raw('<h6 class="text-center">Because: </h6>') %>
            <div class="d-coulumn justify-content-center">
                <% @entity.errors.full_messages.each_with_index do |message, index|%>
                <br><p class="d-column justify-content-start"><%=  index+1 %>. <%= message %> </p>
               <%end%>
            </div>
          <%end%>
        </div>
        <div class="col-md-6  card p-4 m-5">
           <%=  form_with model:  @entity, url: user_group_entities_path, data: { turbo:false } do |f| %>
           <%= f.text_field :name, placeholder:'Transaction', class: 'form-control p-3 my-3'%>
           <%= f.number_field :amount,  placeholder: 'Amount', min:'0',  class: 'form-control p-3 my-3'%>
           <div class="form-control p-3 my-3">
            <%= f.label :category %>
            <%= f.collection_select :group_id, Group.where(user_id: current_user.id).order(:name),:id,:name %>
          </div>
           <div class="d-flex justify-content-end">
            <%= f.submit "Save", disable_with: 'Submiting...', class:'btn btn-success p-3 d-flex justify-content-end' %>
           </div>
           <% end %>
        </div>
    </div>
</div>

app/views/entities/show.html.erb
<div class= "transaction" style="display: flex;
flex-direction: column;
justify-content: center;
align-items: center;
border: 1px solid #eee;
height: 300px;
background: #eee;
width: 50%;
margin: auto;">
<span style="font-size: 30px; color: #000; text-transform: capitalize; font-weight: 600; margin-bottom: 20px;"><%= @entity.name%></span>
<span style="font-size: 15px; color: gray; text-transform: capitalize; font-weight: 400; margin-bottom: 10px;">DATE: <%= @entity.created_at.strftime("%e %B %Y") %></span>
<span style="font-size: 15px; color: gray; text-transform: capitalize; font-weight: 400; margin-bottom: 10px;">TOTAL: $<%= (@entity.amount) %></span>
<% if can? :destroy, @entity %>
<div>
 <%= button_to 'Delete', user_group_entity_path(id: @entity.id), method: :delete,  data: {turbo: false}, class: 'btn bg-danger', style: "color: white; margin-bottom: 10px;" %>
 </div>
 <% end %>
</div>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div style="display:none">
    <%= form.label :Owner, style: "display: none" %>
    <%= form.number_field :user_id,
    value:current_user.id
    %>
  </div>
  <div>
    <%= form.label :icon, style: "display: block" %>
    <%= form.text_field :icon %>
  </div>
  

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div>
<section class= "category_card">

<div class="category-data">
<div class="iimg-icon">
<%= image_tag group.image, skip_pipeline: true, class:'icon'%>
</div>
<div class="name-date">
<h2 class= "category_name"> <%= group.name %></h2>
 <span class="bottom_data">
      <time data="<%= group.created_at %>" class="date"> DATE: <%= group.created_at.strftime("%e %B %Y") %></time>
 </span>
 </div>
<span class= "category_total"><%= number_to_currency(group.total_amount)%></span>
</div>
</section> 
</div> 

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<header>
<h1 class="category-title">Categories</h1>
</header>

<main>
 <% if @groups.any? %>
  <% @groups.each do |group| %>
  <%= link_to render(group), user_group_entities_url(current_user, group.id), class: 'category_wrapper'%> 
<% end %> 
 <% else %>
 <p style="margin-top: 50px; text-align:center; color: orange; font-weight:bold;">
    There is no category added yet!
  </p>
<% end %>
</main>

<footer class="footer">
<%= link_to "Add a new category", new_user_group_path(current_user), class: "add-cat" %>
</footer>

app/views/groups/new.html.erb
<%= form_with model: @group, :html => { :style => "width: 76%; margin: auto; gap: 10px;  border: 1px solid #eee;" }, url: user_groups_path,local: true, data: {turbo:false}  do |form| %>
 
  <div style= "margin-bottom: 20px;    margin-bottom: 20px; display: flex; flex-direction: column;">
 <div>
  <%= image_tag('user.png', style:'width: 200px; height: 200px; margin: auto;') %>
    <%= form.file_field :image %>
  </div> 
  <div>
    <%= form.text_field :name, class: "form-control w-50", placeholder: "Name" , style: ' padding: 10px; margin: auto;' %>
  </div>
    <div class="text-center m-3">
      <%= form.submit "Save", class: "btn btn-primary" %>
    </div>
    <% if @group.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>
  
        <ul>
          <% @group.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% end %>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>

<div>
  <%= link_to "Edit this group", edit_group_path(@group) %> |
  <%= link_to "Back to groups", groups_path %>

  <%= button_to "Destroy this group", @group, method: :delete %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light " style ="background: #3778c2; height: auto">
  <div class="container-fluid">
  <%= link_to 'My costs', root_path, style: "text-decoration: none; color: #deef; font-size: 30px; font-weight: 600; padding-left: 20px;height:auto" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav me-auto" style= "flex-direction: row; width: 100%;justify-content: end; padding-right: 120px;">
     
             <% if user_signed_in? %>
         <li >
         <li style="color: white; font-size: 20px; font-weight: 100;">
         <%= current_user.username   %> 
         <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-default btn-sm" ,style: "color: red; font-size: 20px; font-weight: 100;" %>

         </li>
 </li>
<% else  %>
       <li > 
        <%= link_to "Log in" ,root_path , class: "btn btn-default btn-sm" ,style: "color: blue; font-size: 20px; font-weight: 100;" %>
 </li>


<% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Costs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    "application", :media => "all" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
 
    <%= yield %>
  </body>
</html>

app/views/splashs/index.html.erb
<section class="pages-screen" >
<h1 class= "tittle">My costs</h1>
<div class= "pages-div">
<%= link_to 'Log-in', user_session_path, class: 'sign' %>
<%= link_to 'Sign up', new_user_registration_path, class: 'sign'%>
</div>
</section>